//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.07 at 11:44:58 AM CEST 
//


package net.erel.maven.plugins.domain.changelog;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.erel.maven.plugin.domain.changelog package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Document_QNAME = new QName("http://maven.apache.org/changes/1.0.0", "document");
    private final static QName _ActionDueto_QNAME = new QName("http://maven.apache.org/changes/1.0.0", "dueto");
    private final static QName _ActionFixes_QNAME = new QName("http://maven.apache.org/changes/1.0.0", "fixes");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.erel.maven.plugin.domain.changelog
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ChangesDocument }
     * 
     */
    public ChangesDocument createChangesDocument() {
        return new ChangesDocument();
    }

    /**
     * Create an instance of {@link FixedIssue }
     * 
     */
    public FixedIssue createFixedIssue() {
        return new FixedIssue();
    }

    /**
     * Create an instance of {@link Release }
     * 
     */
    public Release createRelease() {
        return new Release();
    }

    /**
     * Create an instance of {@link Body }
     * 
     */
    public Body createBody() {
        return new Body();
    }

    /**
     * Create an instance of {@link Action }
     * 
     */
    public Action createAction() {
        return new Action();
    }

    /**
     * Create an instance of {@link DueTo }
     * 
     */
    public DueTo createDueTo() {
        return new DueTo();
    }

    /**
     * Create an instance of {@link Author }
     * 
     */
    public Author createAuthor() {
        return new Author();
    }

    /**
     * Create an instance of {@link Properties }
     * 
     */
    public Properties createProperties() {
        return new Properties();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChangesDocument }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://maven.apache.org/changes/1.0.0", name = "document")
    public JAXBElement<ChangesDocument> createDocument(ChangesDocument value) {
        return new JAXBElement<ChangesDocument>(_Document_QNAME, ChangesDocument.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DueTo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://maven.apache.org/changes/1.0.0", name = "dueto", scope = Action.class)
    public JAXBElement<DueTo> createActionDueto(DueTo value) {
        return new JAXBElement<DueTo>(_ActionDueto_QNAME, DueTo.class, Action.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FixedIssue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://maven.apache.org/changes/1.0.0", name = "fixes", scope = Action.class)
    public JAXBElement<FixedIssue> createActionFixes(FixedIssue value) {
        return new JAXBElement<FixedIssue>(_ActionFixes_QNAME, FixedIssue.class, Action.class, value);
    }

}
